export const SET_INTERVIEW_LOADER = 'SET_INTERVIEW_LOADER';
export const REMOVE_INTERVIEW_LOADER = 'REMOVE_INTERVIEW_LOADER';
export const SET_SINGLE_INTERVIEW = 'SET_SINGLE_INTERVIEW';
export const SET_SIMILAR_INTERVIEW = 'SET_SIMILAR_INTERVIEW';
export const SET_INTERVIEW_ERRORS = 'SET_INTERVIEW_ERRORS';
export const REMOVE_INTERVIEW_ERRORS = 'REMOVE_INTERVIEW_ERRORS';
export const SET_NEW_INTERVIEWS = 'SET_NEW_INTERVIEWS';