export const SET_PROFILE_LOADER = 'SET_PROFILE_LOADER';
export const REMOVE_PROFILE_LOADER = 'REMOVE_PROFILE_LOADER';
export const SET_PASSWORD_LOADER = 'SET_PASSWORD_LOADER';
export const REMOVE_PASSWORD_LOADER = 'REMOVE_PASSWORD_LOADER';
export const SET_PROFILE_ERRORS = 'SET_PROFILE_ERRORS';
export const REMOVE_PROFILE_ERRORS = 'REMOVE_PROFILE_ERRORS';
export const SET_PROFILE_MESSAGE = 'SET_PROFILE_MESSAGE';
export const REMOVE_PROFILE_MESSAGE = 'REMOVE_PROFILE_MESSAGE';
