export const SET_SINGLE_LOADER = 'SET_SINGLE_LOADER';
export const REMOVE_SINGLE_LOADER = 'REMOVE_SINGLE_LOADER';
export const SET_SINGLE_ERRORS = 'SET_SINGLE_ERRORS';
export const REMOVE_SINGLE_ERRORS = 'REMOVE_SINGLE_ERRORS';
export const SET_SINGLE_MOVIE = 'SET_SINGLE_MOVIE';
export const SET_SIMILAR_MOVIE = 'SET_SIMILAR_MOVIE';